/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xs0_libs_j15_raw_J15Native */

#ifndef _Included_com_xs0_libs_j15_raw_J15Native
#define _Included_com_xs0_libs_j15_raw_J15Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdInit
  (JNIEnv *, jclass);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdDeInit
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdDeInit
  (JNIEnv *, jclass);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdConnect
 * Signature: ([CZZLcom/xs0/libs/j15/raw/lgLcdOnConfigureCB;Ljava/lang/Object;Lcom/xs0/libs/j15/raw/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdConnect
  (JNIEnv *, jclass, jcharArray, jboolean, jboolean, jobject, jobject, jobject);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdDisconnect
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdDisconnect
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdEnumerate
 * Signature: (IILcom/xs0/libs/j15/raw/lgLcdDeviceDesc;)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdEnumerate
  (JNIEnv *, jclass, jint, jint, jobject);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdOpen
 * Signature: (IILcom/xs0/libs/j15/raw/lgLcdOnSoftButtonsCB;Ljava/lang/Object;Lcom/xs0/libs/j15/raw/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdOpen
  (JNIEnv *, jclass, jint, jint, jobject, jobject, jobject);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdClose
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdClose
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdReadSoftButtons
 * Signature: (ILcom/xs0/libs/j15/raw/IntHolder;)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdReadSoftButtons
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdUpdateBitmap
 * Signature: (II[BI)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdUpdateBitmap
  (JNIEnv *, jclass, jint, jint, jbyteArray, jint);

/*
 * Class:     com_xs0_libs_j15_raw_J15Native
 * Method:    _lgLcdSetAsLCDForegroundApp
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_xs0_libs_j15_raw_J15Native__1lgLcdSetAsLCDForegroundApp
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
